### ISSUE TITLE
Suggestion: Cite the following papers 

### ISSUE THREAD

**Issue by FinAminToastCrunch** [harvard-edge/cs249r_book#304]
In reference to [Ethical Considerations on Pruning](https://harvard-edge.github.io/cs249r_book/contents/optimizations/optimizations.html#legal-and-ethical-considerations), I would suggest citing:

Tran, Cuong, et al. "Pruning has a disparate impact on model accuracy." Advances in neural information processing systems 35 (2022): 17652-17664.

As it discusses how pruning can harm accuracy with respect to inferencing on certain ethnicities. 

In reference to [Establishing Criteria for Pruning](https://harvard-edge.github.io/cs249r_book/contents/optimizations/optimizations.html#establishing-a-criteria-for-pruning), I believe these two papers would be relevant to cite for the portions on importance scores as they tie together more recent work concerning gradient flow and neuron magnitude: 

J. Rachwan, D. Z ̈ugner, B. Charpentier, S. Geisler, M. Ayle, and
S. G ̈unnemann, “Winning the lottery ahead of time: Efficient early
network pruning,” in International Conference on Machine Learning,
ICML 2022, 17-23 July 2022, Baltimore, Maryland, USA (K. Chaudhuri,
S. Jegelka, L. Song, C. Szepesv ́ari, G. Niu, and S. Sabato, eds.),
vol. 162 of Proceedings of Machine Learning Research, pp. 18293–
18309, PMLR, 2022.

E. S. Lubana and R. P. Dick, “A gradient flow framework for analyzing
network pruning,” CoRR, vol. abs/2009.11839, 2020.

**Comment by FinAminToastCrunch** [comment]
Fixed: 

https://harvard-edge.github.io/cs249r_book/contents/optimizations/optimizations.html#legal-and-ethical-considerations

**Comment by profvjreddi** [comment]
Thanks Fin! Do you think you could issue a PR so that I could review it and
merge it in? I will edit it if needed after you issue a PR.

Vijay Janapa Reddi, Ph. D. |
John L. Loeb Associate Professor of Engineering and Applied Sciences |
John A. Paulson School of Engineering and Applied Sciences |
Science and Engineering Complex (SEC) | 150 Western Ave, Room #5.305 |
Boston, MA 02134 |
Harvard University | My Website
<http://scholar.harvard.edu/vijay-janapa-reddi> | Google Scholar
<https://scholar.google.com/citations?hl=en&user=gy4UVGcAAAAJ&view_op=list_works&sortby=pubdate>
 | Edge Computing Lab <https://edge.seas.harvard.edu> | Book Meeting
<https://fantastical.app/vjreddi/> | Contact Admin
<https://scholar.harvard.edu/vijay-janapa-reddi/contact> |

**Comment by profvjreddi** [comment]
And just as FYI. I typically avoid incorporating overly cutting-edge
material into the book. The criterion for inclusion is that the industry
must be actively adopting and utilizing the methods discussed. This
approach ensures the content remains relevant and avoids delving into an
excessive number of rapidly evolving topics. Does that make sense?

Vijay Janapa Reddi, Ph. D. |
John L. Loeb Associate Professor of Engineering and Applied Sciences |
John A. Paulson School of Engineering and Applied Sciences |
Science and Engineering Complex (SEC) | 150 Western Ave, Room #5.305 |
Boston, MA 02134 |
Harvard University | My Website
<http://scholar.harvard.edu/vijay-janapa-reddi> | Google Scholar
<https://scholar.google.com/citations?hl=en&user=gy4UVGcAAAAJ&view_op=list_works&sortby=pubdate>
 | Edge Computing Lab <https://edge.seas.harvard.edu> | Book Meeting
<https://fantastical.app/vjreddi/> | Contact Admin
<https://scholar.harvard.edu/vijay-janapa-reddi/contact> |

**Comment by FinAminToastCrunch** [comment]
Done! 

And yes, makes sense.

**Comment by profvjreddi** [comment]
Dealt with in issue https://github.com/harvard-edge/cs249r_book/pull/306 and PR

**Comment by profvjreddi** [comment]
Thanks @FinAminToastCrunch I finally got a chance to review the changes and make some tweaks an close it.
