### ISSUE TITLE
Typos in "data_engineering.qmd"

### ISSUE THREAD

**Issue by BravoBaldo** [harvard-edge/cs249r_book#358]
In "data_engineering.qmd":

- "...and enable algorithms to learn more robust patterns." --maybe "...and enable algorithms to **teach/train** more robust patterns."
- "Health Information Exchanges(HIEs)" space before '('
- "Anamoly Detection:" --> "**Anomaly** Detection" (4 occurrences!)

Baldo

**Comment by profvjreddi** [comment]
Thanks, @BravoBaldo. I will push those fixes. 

By the way, if you'd like to contribute, you are more than welcome to issue a PR for this. Just saying, but don't feel obligated. I just want to make sure that everyone feels comfortable doing so, because I do want us all to work together; it is an open-source project 📖
