### ISSUE TITLE
Please update info...

### ISSUE THREAD

**Issue by BravoBaldo** [harvard-edge/cs249r_book#387]
In "hw_acceleration.qmd", section "10.8.7 Quantum Computing"
...."`The largest quantum computer today has less than 100 qubits.`"

... see Osprey by IBM it is 433 qubits (https://en.wikipedia.org/wiki/IBM_Osprey)

...or rephrase the statements ;)

See also next statements ...

**Comment by profvjreddi** [comment]
Things change fast! Thanks for catching that. I updated it to say less than 1k bits :) Future proofing! 

> See also next statements ...

Not following what you mean by this.

**Comment by profvjreddi** [comment]
By the way @BravoBaldo I added you as a contributor, so that I can recognize your effort in helping me improve the material. Hope that's OK! That means you will show up in [contrib](https://harvard-edge.github.io/cs249r_book/contents/contributors.html) so please let me know if you are alright with that.

**Comment by BravoBaldo** [comment]
Thank you, I'm honored, but I'm just a reader ;)

Baldo

**Comment by profvjreddi** [comment]
Hi Baldo,

I appreciate your humility, but I want you to know that your suggestions are valuable, whether big or small. Not too many readers take the time to provide such specific feedback, and your suggestions benefit everyone who engages with the material. That's why I want to recognize your time and effort and give special thanks!

Thank you once again for all your help! 🙏
