### ISSUE TITLE
First part of "robust_ai.qmd"

### ISSUE THREAD

**Issue by BravoBaldo** [harvard-edge/cs249r_book#440]
- In "Introduction",
 	- Search "in the presence of hardware, software, and errors." --> maybe "in the presence of hardware[, human] and software errors."
 	- The 'introduction' of the list refer to errors Hw, Sw and Human but next 'human' is missing and appears 'Model Robustness' ! 
- Search "SDCS" the first occurrence must be "SDCs" (s in lowercase)
- The link about fault of "Boeing 787" ("https://www.engineering.com/story/vzrxw") is broken
- Search "Show a real-world example from" ---> "S" must be in lowercase
- Please review titles of sub-section of  "17.5 Software Faults" they are not numbered
- "17.4.1 Adversarial Attacks" is almost the same as "14.4.3 Adversarial Attacks" in "privacy_security.qmd". Please review.
- in "robust_ai.qmd", search "\-\--" please verify result.
- Search "fall under black black-box box grey-boxes." please review sentence.
- "17.4.2 Data Poisoning" is almost the same as "14.4.2 Data Poisoning" in "privacy_security.qmd". Please review.

P.S.:
In "sustainable_ai", "design systems hardware with environmental impact in mind." ---> first D in uppercase

**Comment by profvjreddi** [comment]
Thanks @BravoBaldo for the feedback!



> "17.4.2 Data Poisoning" is almost the same as "14.4.2 Data Poisoning" in "privacy_security.qmd". Please review.

Ah, good catch! We were trying to move content out of the privacy and security chapter when writing this chapter, so that makes sense! 

> * Search "in the presence of hardware, software, and errors." --> maybe "in the presence of hardware[, human] and software errors."

Ah I thought I had removed the human element, but you are right its still there. It gets too messy with human errors. Too many to focus on, but I suppose we should keep it for coverage perspective because that is a real form of error.

> * The link about fault of "Boeing 787" ("https://www.engineering.com/story/vzrxw") is broken

I updated this... and the rest! 🙏
